kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ???               # Name für Volume Claim angeben - dieser Name muss später in der Pod oder Deployment Spezifikation verwendet werden
spec:
  storageClassName: ???   # Gültige StorageClass angeben. Aktuell im Cluster vorhanden können via "kubectl get storageclass" angezeigt werden
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ???        # Größe des zu erstellenden Volumes 
