apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-int-lb
  labels:
    app: hello-kubernetes
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes
  type: LoadBalancer