apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-np
  labels:
    app: hello-kubernetes-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes
  type: NodePort