apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello                                                # Name des  Cronjobs
spec:
  schedule: "*/5 * * * *"                                    # Zeitplan in Crontab Format
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello                                      # Spezifikation des auszuführenden
            image: busybox:1.28                              # Containers inkl. Argumente
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

